project:
  type: book
  output-dir: _site
  resources:
    - "assets/*"
  render:
    - "*.qmd"
    - "*.Rmd"
    - "!*.md"
    - "!README.md"
    - "!LICENSE.md"

book:
  title: "Infectious Diseases for Data Scientists"
  date: today
  author: 
  - name: "Michael E. DeWitt"
    orcid: "0000-0001-8940-1967"


  page-navigation: true
  cover-image: "assets/cholera_in_paris_2002.136.8.jpg"
  chapters:
    - index.qmd
    - introduction.qmd

    - part: chapter/data/data.qmd
      chapters:
      - chapter/data/surveillance.qmd
    - part: chapter/lab/methods.qmd
      - chapter/lab/immunochemistry.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-link: true
    author-meta: "Michael E. DeWitt"
  pdf:
    documentclass: scrreprt
  epub:
    toc: true
    lang:
      en-GB
    date:
      "2023-07-24"
#  typst: default


# Other Formattinging stuff
callout-icon: false

execute:
  freeze: auto
